### ISSUE TITLE
Help cannot link

### ISSUE THREAD

**Issue by Tippolo** [DiscowZombie/UltimateTs#14]
Hi

I configure ts3 server in my linuxbox and minecraft server too.

I put username and password (the nickname and password used to claim the admin token  in ts3). restart minecraft and receive the message in console:
[UltimateTs] Enabling UltimateTs v2.1.4
[UltimateTs] (TeamSpeak) Bot Online!
[UltimateTs] (Sql) Connection successfully.
[UltimateTs] UltimateTs | v2.1.4 | Author: DiscowZombie.
[UltimateTs] Using 1.11.2-R0.1-SNAPSHOT | git-Spigot-3fb9445-6e3cec8 (MC: 1.11.2) | v1_11_R1.
[UltimateTs] Your perms system is Vault.
[UltimateTs] You can links ranks with Vault.
[UltimateTs] Using SQL as storage type.

When I log into ts3 I have 2 client online.

In minecraft I digit /ts link and then log in ts3 with the same nick as minecraft name. Nothing happen.
command $ping not working
Comand $info not working

Help please

**Comment by Tippolo** [comment]
Now work (not $ping or $info) but /ts broadcast works.

Just create a query login in ts server and put the username and password with the query login (create it with the server admin account).

:)

**Comment by Tippolo** [comment]
Cannot link help!!

Now $ping and $info work. I try to use /ts link receive the message Your mc account...
log into ts3 server with the same username as minecraft and nothing happen..

**Comment by DiscowZombie** [comment]
Hi,

probably you haven't read the Insall part... 
`Before start installing, you need:

    A minecraft server off ;
    A TeamSpeak server running ;
    You Admin Query password (gived when you start your TeamSpeak server for the first time!) ;

If you have any question about Admin Query on TeamSpeak, read this: http://media.teamspeak.com/ts3_literature/TeamSpeak 3 Server Query Manual.pdf.

Warning: To avoid losing access to your TeamSpeak server, it is highly recommended that you create a privilege key BEFORE you start the bot for the first time (key you can use in case of problems).

Now you can start:

    First, download the plugin ;
    Drag and drop the plugin into your /plugins folder ;

Start your server. It's possible that UltimateTs generated error, it's normal. Now, stop your server.

    Now, a new folder will be created (plugins/UltimateTs).
    You can now go to the configuration file (plugins/UltimateTs/config.yml). You need to add you TeamSpeak server IP & your password:

Code (Text):
login:
#Change by your TeamSpeak server IP (WITHOUT PORT)
  ip: localhost
  username: serveradmin
  password: password
#Port of your TeamSpeak server
  port: 9987
bot:
#A name for the bot !
  name: UltimateTs

    You can choose to use a database (to save your linked players in database) or to save in this file. If you want to use a database, enter your informations here:

Code (Text):
database:
  enable: false
  host: localhost
  name: databaseName
  user: root
  password: password
Else, leave this.

    You can choose if players were kicked when they joined the TeamSpeak and aren't registered by changing this:

Code (Text):
config:
#Kick players if they haven't linked her account
  kickNotRegister: false

    Now, you need to change the value of

Code (Text):
defaultGroupId
by the value of your default group on TeamSpeak (My default rank on TeamSpeak is guest with the id 8).
[​IMG]

If you want all your linked players to get a special rank on TeamSpeak, you can by changing:
Code (Text):
asignWhenregister
by the id of your TeamSpeak ranks.

Now, you need to define linked TeamSpeak ranks for your players. The ranks system is baised on permissions. Add this:
Code (Text):
  perms:
    exemplePerms: 10
exemplePerms is your permission and 10 is the ranks to link. In each permissions plugin, all ranks had the permission group.<name of rank> (or rank.<name of rank> depend on your PemissionSystem). Then, to link your ranks, add the permission group.<name of rank> (or rank.<name of rank> depend on your PemissionSystem) and the id of your TeamSpeak ranks.

You can add an infinit numbers of permissions !


    When you are finish configs all ranks and messages (you can modify all messages in UltimateTs/messages.yml), you can save and run you server !

Warning: Before editing configuration, ALWAYS STOP your server.

    To be sure that the Bot is online, there are several solutions:

- You can check the console, if she said "Bot online!" when starting the server, it's ok !
[​IMG]

- Click on your TeamSpeak server. If "Current Query" equals one, it's ok.
[​IMG]
- Go to the default channel and type $ping. If the bot reply with "pong!", it's ok.
[​IMG]

That's perfect, your players can now link there accounts. If you have any problem, question or sugest, open a new issues on github: https://github.com/DiscowZombie/UltimateTs/issues.`

> I put username and password (the nickname and password used to claim the admin token in ts3)
You need to use a ADMIN SERVER QUERY ACCOUNT, NOT YOUR MYTEAMSPEAK ACCOUNT.

> Just create a query login in ts server and put the username and password with the query login (create it with the server admin account).
Please use the default admin server query account or ensure that this query has "server query admin" rank else commands will not working because of miss permissions !

> log into ts3 server with the same username as minecraft and nothing happen..
The same username is not needed, just have the same IP (should also work with a VPN)

> I use luckperms

[UltimateTs] Your perms system is Vault.
[UltimateTs] You can links ranks with Vault.
Verify that Vault is up-to-date. 

What version of Minecraft do you use?


Also, keep in mind this :
> IMPORTANTE NOTE - Monday 28/08/17 : Unfortunately, my disponibility doesn't allow me to update and fix issues of this plugin. Updates will be rare, as like fixes (But the project isn't abandoned. I make updates when I get more times). Source code remains accessible and I would continue to accept "Pull Request" and commits them to the master branch. I thank, in advance, all the people who participate in the source code to make the plugin better.

**Comment by Tippolo** [comment]
Minecraft server 1.11.2, vault latest query account made, I can make $ping and $info but no link account (I have a linux with mc server andts server working) try login via internal network (maybe this?) now I try to log in ts and minecraft outside the lan (internet).

**Comment by Tippolo** [comment]
Solved....outside the lan all works fine thanks a lot :)

**Comment by DiscowZombie** [comment]
Ok, fantastic !
